######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 27 11:47:51 2016
######################################################################
QT     +=core widgets
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h qupdatethread.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp qupdatethread.cpp

target.path= /root
INSTALLS+=target sources
